//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public long Id { get; set; }
        public decimal Monto { get; set; }
        public string Comentario { get; set; }
        public System.DateTime Fecha { get; set; }
        public long MonedaId { get; set; }
        public long ProveedorId { get; set; }
        public bool Estado { get; set; }
        public long UserReg { get; set; }
        public System.DateTime FechaReg { get; set; }
        public Nullable<long> UserMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
